version: '3.7'
services:
  api:
    build: ./
    container_name: api
    command: [ "yarn", "run", "start" ]
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    networks:
      - api

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
#    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api

networks:
  api:
    name: api_network
    driver: bridge
