export enum EUserRole {
  USER = 'USER',
  ADMIN = 'ADMIN',
  VIEWER = 'VIEWER',
}
export enum EDepartment {
  COMPANY = 'COMPANY',
  UNKNOWN = 'UNKNOWN',
  DEVELOPMENT = 'DEVELOPMENT',
  PRODUCT = 'PRODUCT',
  ADMINISTRATION = 'ADMINISTRATION',
  MARKETING = 'MARKETING',
  DESIGN = 'DESIGN',
  HR = 'HR',
}

export enum EPosition {
  UNKNOWN = 'UNKNOWN',
  DEVELOPER_SENIOR = 'DEVELOPER_SENIOR',
  DEVELOPER_JUNIOR = 'DEVELOPER_JUNIOR',
  QA_JUNIOR = 'QA_JUNIOR',
  QA_LEAD = 'QA_LEAD',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
}

export enum EUserStatus {
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  INACTIVE = 'INACTIVE',
  DEACTIVATED = 'DEACTIVATED',
}
