export enum EUserStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
}

export enum EUserRole {
  VIEWER = 'VIEWER',
  MANAGER = 'MANAGER',
  ADMIN = 'ADMIN',
}
export enum EDepartment {
  COMPANY = 'COMPANY',
  DEVELOPMENT = 'DEVELOPMENT',
  ADMINISTRATION = 'ADMINISTRATION',
  DESIGN = 'DESIGN',
  PRODUCT = 'PRODUCT',
  MARKETING = 'MARKETING',
  HR = 'HR',
}

export enum EPosition {
  DEVELOPER_SENIOR = 'DEVELOPER_SENIOR',
  DEVELOPER_JUNIOR = 'DEVELOPER_JUNIOR',
  QA_JUNIOR = 'QA_JUNIOR',
  QA_LEAD = 'QA_LEAD',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
}
