### test login
GET http://localhost:{{port}}/{{prefix}}/{{version}}/auth/test/admin@pulsopus.dev


### login
POST http://localhost:{{port}}/{{prefix}}/{{version}}/auth/login
Content-Type: application/json

{
  "login": "admin@pulsopus.dev",
  "password": "password"
}

### token login
POST http://localhost:{{port}}/{{prefix}}/{{version}}/auth/token
Content-Type: application/json
Authorization: Bearer {{$auth.token("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Njk2ZWQ2YmZkOTY5MjQ4N2E0Zjk1MTciLCJ1c2VybmFtZSI6ImFkbWluIHRlc3QiLCJyb2xlIjoiQURNSU4iLCJzdGF0dXMiOiJBQ1RJVkUiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNzIxNjI5NDE5LCJleHAiOjE3MjE2MzI5NTl9.sR3EnehLIZ1p2jIu2vf16IW8sp_sywX1mXSMt8Puyhc")}}


### register full host
POST http://167.99.248.5:{{port}}/{{prefix}}/auth/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "admin@plusopus.com",
  "password": "admin"
}

### register full
POST http://localhost:{{port}}/{{prefix}}/auth/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "admin@mail.com",
  "password": "admin"
}

### register empty
POST http://localhost:{{port}}/{{prefix}}/auth/register
Content-Type: application/json

{}

### login full
POST http://localhost:{{port}}/{{prefix}}/auth/login
Content-Type: application/json

{
  "username": "admin@mail.com",
  "password": "admin"
}

### login empty
POST http://localhost:{{port}}/{{prefix}}/auth/login
Content-Type: application/json

{}

### get me
GET http://localhost:{{port}}/{{prefix}}/auth/current
Authorization: Bearer {{token}}

### logout
GET http://localhost:{{port}}/{{prefix}}/auth/logout
Authorization: Bearer {{token}}

### refresh full
GET http://localhost:{{port}}/{{prefix}}/auth/refresh
Authorization: Bearer {{refreshToken}}


