export const AUTH_JWT_ACCESS_TYPE = 'AUTH_JWT_ACCESS_TYPE';
export const AUTH_JWT_REFRESH_TYPE = 'AUTH_JWT_REFRESH_TYPE';

export const USE_PUBLIC_KEY = 'USE_PUBLIC_KEY';

export const USE_ROLES_KEY = 'USE_ROLES_KEY';
